# Generated by Django 5.0.7 on 2024-07-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0002_contact_submitted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
