# Generated by Django 5.0.7 on 2024-07-25 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0003_alter_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="birth_date",
            field=models.DateField(default="2022-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="marital_status",
            field=models.CharField(default="Single", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="nationality",
            field=models.CharField(default="Tchadienne", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                ("proficiency", models.CharField(max_length=50)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="siteweb.resume",
                    ),
                ),
            ],
        ),
    ]
