# Generated by Django 5.0.7 on 2024-07-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteweb", "0004_resume_birth_date_resume_marital_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="address",
            field=models.CharField(default="Lomé", max_length=200),
            preserve_default=False,
        ),
    ]
